version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./src:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    tty: true
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: ./docker/laravel/Dockerfile
    # portを9000にする。Nginxとの兼ね合い
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/app
    working_dir: /var/www/app
#    command: php artisan serve --host 0.0.0.0
    tty: true
    restart: always
    depends_on:
      - db
    links:
      - db

  db:
    container_name: laravel-ecr-test
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      TZ: 'Asia/Tokyo'